from django.core.management import utils

with open('secrets.py', 'w+') as fake_secrets_file:
    fake_secrets_file.write('# Autogenerated, fake secrets file.\n')

    fake_secrets_file.write('SECRET_KEY = \'{}\'\n'.format(utils.get_random_secret_key()))

    fake_secrets_file.write('MARIADB_USER = \'physics\'\n')
    fake_secrets_file.write('MARIADB_DB = \'physics\'\n')
    fake_secrets_file.write('MARIADB_PASSWORD = \'physics\'\n')
    fake_secrets_file.write('MARIADB_HOST = \'localhost\'\n')
